# Generated by Django 3.1 on 2020-08-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=500, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('contact_type', models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Relative', 'Relative')], max_length=500, null=True)),
                ('patient_relationship', models.CharField(blank=True, choices=[('Self', 'Self'), ('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_type', models.CharField(blank=True, choices=[('Home', 'Home'), ('Mobile', 'Mobile'), ('Work', 'Work')], max_length=500, null=True)),
                ('primary', models.BooleanField(blank=True, default=True, null=True)),
                ('patient_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientcontact')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=500, null=True)),
                ('patient_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientcontact')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=500, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.insurance')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
