# Generated by Django 3.1 on 2020-08-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='CompanyB00',
        ),
        migrations.RenameModel(
            old_name='Insurance',
            new_name='InsuranceB00',
        ),
        migrations.RenameModel(
            old_name='InsuranceRepresentative',
            new_name='InsuranceB01',
        ),
        migrations.RenameModel(
            old_name='PatientAddress',
            new_name='PatientAddressB01',
        ),
        migrations.RenameModel(
            old_name='PatientContact',
            new_name='PatientContactB00',
        ),
        migrations.RenameModel(
            old_name='PatientPhone',
            new_name='PatientPhoneB02',
        ),
    ]
