# Generated by Django 3.1 on 2020-08-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200821_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFamilyB05S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('mother', models.BooleanField(default=False)),
                ('mother_side', models.BooleanField(default=False)),
                ('father', models.BooleanField(default=False)),
                ('father_side', models.BooleanField(default=False)),
                ('brother', models.BooleanField(default=False)),
                ('sister', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralQuestionsCategoryB04R',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientSiblingB03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Brother', 'Brother'), ('Sister', 'Sister')], max_length=500, null=True)),
                ('age', models.CharField(blank=True, max_length=500, null=True)),
                ('patient_contact_b00_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientcontactb00')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientHistoryB07',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('patient_contact_b00_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientcontactb00')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientGrowthB06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('when', models.BooleanField(default=False)),
                ('patient_contact_b00_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientcontactb00')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralQuestionB04S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('question_type', models.CharField(blank=True, max_length=500, null=True)),
                ('question_extended', models.CharField(blank=True, max_length=500, null=True)),
                ('patient_general_question_category_b04r_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientgeneralquestionscategoryb04r')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientGeneralQuestionB04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('question_extended', models.CharField(blank=True, max_length=500, null=True)),
                ('patient_general_question_category_b04s_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientgeneralquestionb04s')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientFamilyB05',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('mother', models.BooleanField(default=False)),
                ('mother_side', models.BooleanField(default=False)),
                ('father', models.BooleanField(default=False)),
                ('father_side', models.BooleanField(default=False)),
                ('brother', models.BooleanField(default=False)),
                ('sister', models.BooleanField(default=False)),
                ('patient_contact_b00_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientcontactb00')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
