# Generated by Django 3.1 on 2020-08-25 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patientfamilyb05_patientfamilyb05s_patientgeneralquestionb04_patientgeneralquestionb04s_patientgener'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLocationM01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationM00',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicationFrequencyB08R2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('frequency', models.CharField(blank=True, max_length=500, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicationRouteB08R1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('route', models.CharField(blank=True, max_length=500, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicationB08',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('medication_type', models.CharField(blank=True, max_length=500, null=True)),
                ('medication', models.CharField(blank=True, max_length=500, null=True)),
                ('dose', models.CharField(blank=True, max_length=500, null=True)),
                ('prescribed_by', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('patient_contact_b00_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientcontactb00')),
                ('patient_medication_frequency_b08r2_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientmedicationfrequencyb08r2')),
                ('patient_medication_route_b08r1_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientmedicationrouteb08r1')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationStaffM03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=500, null=True)),
                ('organization_location_m01_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.organizationlocationm01')),
                ('organization_m00_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.organizationm00')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationLocationRoomM02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField()),
                ('organization_location_m01_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.organizationlocationm01')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='organizationlocationm01',
            name='organization_m00_rec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.organizationm00'),
        ),
        migrations.CreateModel(
            name='AppointmentB00',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('purpose', models.TextField()),
                ('scheduled_by', models.CharField(blank=True, max_length=250, null=True)),
                ('organization_location_m01_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.organizationlocationm01')),
                ('organization_location_room_m02_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.organizationlocationroomm02')),
                ('patient_contact_b00_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.patientcontactb00')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
